openapi: 3.0.0
info:
  title: "CC2526 Group8"
  description: "A platform which offers unified catalog of movies, a public review system, and a personal watchlist to keep users organize all the titles they interact with. On top of this, the platform includes a recommendation system that suggests future watches based on each user's history."
  version: "1.0.0"
servers:
  - url: "/api"

components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
        email:
          type: string
          format: email
        username:
          type: string

    UserDetails:
      type: object
      properties:
        user_id:
          type: string
        email:
          type: string
          format: email
        username:
          type: string
        gender:
          type: string
          enum: [M, F, NB, O]
        age:
          type: integer
        password_hash:
            type: string

    UserRegistration:
      type: object
      required:
        - email
        - password
        - username
        - termsAccepted
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          description: Must have at least 10 characters and contain at least one number
          minLength: 10
          pattern: "^(?=.*\\d).{10,}$"
        username:
          type: string
        gender:
          type: string
          enum: [M, F, NB, O]
        age:
          type: integer
        termsAccepted:
          type: boolean
          description: Must be true to complete registration

    Rating:
      type: object
      required:
        - rating_id
        - rating
        - user_id
        - movie_id
      properties:
        rating_id:
          type: integer
          enum: [1,2,3,4,5]
        user_id:
          type: string
        movie_id: 
          type: integer
        rating:
          type: integer
        review:
          type: string
        timestamp:
          type: string
          format: date-time
        tag:
          type: string

    UserRating:
      type: object
      required:
        - rating_id
        - rating
        - movie_id
      properties:
        rating_id:
          type: integer
          enum: [1,2,3,4,5]
        movie_id: 
          type: integer
        rating:
          type: integer
        review:
          type: string
        timestamp:
          type: string
          format: date-time
        tag:
          type: string
    
    CreateRating:
      type: object
      required:
        - rating
        - user_id
      properties:
        user_id: 
          type: string
        rating:
          type: integer
        review:
          type: string
        timestamp:
          type: string
          format: date-time
        tag:
          type: string  

    UpdateRating:
      type: object
      required:
        - rating
      properties:
        rating:
          type: integer
        review:
          type: string
        timestamp:
          type: string
          format: date-time
        tag:
          type: string  

    MovieRating:
      type: object
      required:
        - rating_id
        - rating
        - user_id
      properties:
        rating_id:
          type: integer
          enum: [1,2,3,4,5]
        user_id:
          type: string
        rating:
          type: integer
        review:
          type: string
        timestamp:
          type: string
          format: date-time
        tag:
          type: string

  parameters:
    user_id:
      name: user_id
      in: path
      required: true
      schema:
        type: string

    rating_id:
      name: rating_id
      in: path
      required: true
      schema:
        type: integer
    
    movie_id:
      name: movie_id
      in: path
      required: true
      schema:
        type: integer
    
    movie_filter:
      name: movie
      in: query
      required: false
      schema:
        type: string

    username_filter:
      name: username
      in: query
      required: false
      schema:
        type: string

    rating_filter:
      name: rating_filter
      in: query
      required: false
      schema:
        type: integer
    
    filter_by_year:
      name: filter_by_year
      in: query
      required: false
      schema:
        type: integer
    
    tag_filter:
      name: tag_filter
      in: query
      required: false
      schema:
        type: string
    
paths:
  /users:
    get:
      summary: Retrieve all users
      operationId: getUsers
      tags:
        - "User Registration"
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Register a new user
      operationId: registerUser
      tags:
        - "User Registration"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistration"
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input (e.g., missing required fields, weak password)

  /users/{user_id}:
    get:
      summary: Retrieve user details
      operationId: getUser
      tags:
        - "User Registration"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        '200':
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
    put:
      summary: Update user details
      operationId: updateUser
      tags:
        - "User Registration"
      parameters:
        - $ref: "#/components/parameters/user_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDetails"
      responses:
        '200':
          description: User updated successfully
    delete:
      summary: Delete a user
      operationId: deleteUser
      tags:
        - "User Registration"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        '204':
          description: User deleted successfully
          
  /auth:
    post:
      summary: Authenticate user and generate a token
      operationId: loginUser
      tags:
        - "User Authetication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Authentication successful, token generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /auth/{user_id}:
    post:
      summary: Invalidate user token
      operationId: logoutUser
      tags:
        - "User Authetication"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        '200':
          description: User logged out successfully
        '401':
          description: Unauthorized

  /auth/verify:
    get:
      summary: Verify if the token is valid
      operationId: verifyToken
      tags:
        - "User Authetication"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        '200':
          description: Token is valid
        '401':
          description: Invalid or expired token

  /ratings:
      get:
        summary: Retrieve all ratings
        operationId: getRatings
        tags:
          - "Review System"
        parameters:
          - $ref: '#/components/parameters/username_filter'
          - $ref: '#/components/parameters/movie_filter'
          - $ref: '#/components/parameters/rating_filter'
          - $ref: '#/components/parameters/filter_by_year'
          - $ref: '#/components/parameters/tag_filter'
        responses:
          '200':
            description: List of rating retrieved successfully
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Rating"

  /ratings/{rating_id}:
    get:
      summary: Retrieve rating by its id
      operationId: getRating
      tags:
        - "Review System"
      parameters:
        - $ref: '#/components/parameters/rating_id'
      responses:
        '200':
          description: Rating retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rating"
    put:
      summary: Update a specific rating
      operationId: updateRating
      tags:
        - "Review System"
      parameters:
        - $ref: "#/components/parameters/rating_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRating'
      responses:
        '200':
          description: User updated successfully
    delete:
      summary: Delete a specific rating
      operationId: deleteRating
      tags:
        - "Review System"
      parameters:
        - $ref: "#/components/parameters/rating_id"
      responses:
        '204':
          description: User deleted successfully
  
  /movies/{movie_id}/ratings:
    get:
      summary: Retrieve movie ratings
      operationId: getMovieRatings
      tags:
        - "Review System"
      parameters:
        - $ref: '#/components/parameters/movie_id'
        - $ref: '#/components/parameters/rating_filter'
        - $ref: '#/components/parameters/filter_by_year'
        - $ref: '#/components/parameters/tag_filter'
      responses:
        '200':
          description: Movie ratings retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieRating"
    post:
      summary: Create a new rating
      operationId: createRating
      tags:
        - "Review System"
      parameters: 
        - $ref: '#/components/parameters/movie_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRating'
      responses:
        '201':
          description: Created movie rating successfully
        '400':
          description: Invalid input (e.g., missing required fields)
  
  /users/{user_id}/ratings/:
    get:
      summary: Retrieve user ratings
      operationId: getUserRatings
      tags:
        - "Review System"
      parameters:
        - $ref: "#/components/parameters/user_id"
        - $ref: '#/components/parameters/rating_filter'
        - $ref: '#/components/parameters/filter_by_year'
        - $ref: '#/components/parameters/tag_filter'
      responses:
        '200':
          description: User ratings retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRating"

